# Generated by Django 3.1.7 on 2023-02-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msbctracker', '0006_alter_tracker_numeric_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='last_event',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='tracking_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
