# Generated by Django 4.1 on 2023-02-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msbctracker', '0007_alter_tracker_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='tracking_number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
